name: test_flutter_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0-88.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_hooks: ^0.20.5
  adaptive_sizer:
    git:
      url: https://github.com/kishormainali/adaptive_sizer
  flutter_svg: ^2.0.10+1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

